### ISSUE TITLE
Can I manually replace/upgrade the fastjson package to the latest version? 

### ISSUE THREAD

**Issue by charlesvhe** [apache/rocketmq#1328]
We are useing rocketmq-all-4.2.0 

fastjson has remote executive issue: https://github.com/alibaba/fastjson/issues/2500

I need to upgrade fastjson to  fastjson-1.2.58.jar, can I just replace the original fastjson.jar in /lib directory？

**Comment by liuruiyiyang** [comment]
No, you can't simply do that. 
If you have to change the version of a dependency, you should change the pom and refactor the related codes, then rebuild the project. However, it is not recommended because it is unsafe and whether the new version is fully compatible is not known.
For the issue of fastjson, we will check it out later and see if we should apply the new version.

**Comment by zongtanghu** [comment]
Hi @charlesvhe we will have a try to upgrade fastjson to fastjson-1.2.58.jar firstly,and then tell you the result.Please keep in touch with the rocektmq community.

**Comment by duhenglucky** [comment]
fixed
