### ISSUE TITLE
Throws ClientErrorCode.CONNECT_BROKER_EXCEPTION in MQClientException when send max times still failed which in DefaultMQProducerImpl.java

### ISSUE THREAD

**Issue by HymanShi** [apache/rocketmq#1362]
- What did you do?
1. Use rmq clinet to send msg to broker
2. Exception happens when retry to max times and the Exception code makes me confused.
3. I read the rmq client code and find it out
- What did you expect to see?
Rmq client give me a exception code clearly, eg:RETRY_TO_FAILED
- What did you see instead?
Throws  ClientErrorCode.CONNECT_BROKER_EXCEPTION in MQClientException when send max times still failed which in DefaultMQProducerImpl.java

- information:
https://github.com/apache/rocketmq/blob/master/client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java#L630

And another important issue is : 
Also in DefaultMQProducerImpl.java#L596
https://github.com/apache/rocketmq/blob/master/client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java#L596
Why  RemotingSysResponseCode.SYSTEM_BUSY is not in the retry list?Which is set in BrokerFastFailure.java when  [TIMEOUT_CLEAN_QUEUE] [PCBUSY_CLEAN_QUEUE] happens

**Comment by duhenglucky** [comment]
@HymanShi As you described, rocketmq indeed need to polish the mechanism to make it more clear and useful for positioning problem, so would you like to polish this together?

The second question, if the producer still retries when the SYSTEM_BUSY exception was responded by the server, it will increase the load of the server, so in order to protect the server,
the producer will stop the retry process.

**Comment by HymanShi** [comment]
> @HymanShi As you described, rocketmq indeed need to polish the mechanism to make it more clear and useful for positioning problem, so would you like to polish this together?
> 
> The second question, if the producer still retries when the SYSTEM_BUSY exception was responded by the server, it will increase the load of the server, so in order to protect the server,
> the producer will stop the retry process.

@duhenglucky Thanks for your invitation, I'd like to polish this mechanism and how can i join it?
Reply to the second question:In fact, when users happen the SYSTEM_BUSY or other exceptions which are not in the retry list,users always resend the message themselves immediately in order to prevent sending failure.It will still increase the load of the server.Maybe rocketmq should provide a self-later-resend mechanism when SYSTEM_BUSY or other exception happens.

**Comment by atris** [comment]
I would like to work on this -- can I be please assigned the same?

**Comment by duhenglucky** [comment]
@atris thanks for your attention and RocketMQ‘s flow control mechanism can be improved indeed, welcome to participate in the improvement.

**Comment by duhenglucky** [comment]
@HymanShi Because there are many changes will be involved, so it is necessary to describe the related design and changes in detail, it would be nice if you can submit a [RIP](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal) in community. I am very glad to help you complete this work.

**Comment by atris** [comment]
Ah, I did not realise @HymanShi is working on this one, sorry about that!

**Comment by HymanShi** [comment]
@duhenglucky Thanks for your invitation and I am willing to participate this.I will submit a RIP in community ASAP!
@atris Never mind!We can work on this together.
