### ISSUE TITLE
clsuterList command get wrong result when different cluster with same name server and same brokerName 

### ISSUE THREAD

**Issue by superheizai** [apache/rocketmq#1450]
![image](https://user-images.githubusercontent.com/3948418/64631569-f45d1780-d429-11e9-96fe-06d666ce45c2.png)

1. firstly, create broker-a.properties

brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
deleteWhen=04
fileReservedTime=48
listenPort=10911
namesrvAddr=localhost:9876
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

startup with broker-a.properties, we can see the right output.

2. secondly, create broker-b.properties
brokerClusterName=DefaultCluster1
brokerName=broker-a
brokerId=0
deleteWhen=04
fileReservedTime=48
listenPort=10921
namesrvAddr=localhost:9876
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
storePathRootDir=~/rocketmq/data/store
storePathCommitLog=~/rocketmq/data/store/commitlog
storePathIndex=~/rocketmq/data/store/index
storePathConsumeQueue=~/rocketmq/data/store/consumequeue

then ClusterList give two broker both with 10921 port

**Comment by superheizai** [comment]
Furthormore, under this situation, I create the topic to DefaultCluster1, the topic would be created to DefaultCluster.
![image](https://user-images.githubusercontent.com/3948418/64632157-24f18100-d42b-11e9-995f-0cb43c1188ac.png)

**Comment by superheizai** [comment]
@duhenglucky This  could be a bug.  In the first picture, which show the same IP:port in different cluster. As I think, this could't happen at any case.

**Comment by CodeIngL** [comment]
在nameServer中，一个broker名字对应一个BrokerData，BrokerData拥有一个clusterName
    private final HashMap<String/* brokerName */, BrokerData> brokerAddrTable;
 所以你要改名
@superheizai

**Comment by superheizai** [comment]
@CodeIngL , I know how to resolve the problem. What I want to know is if this result is RocketMQ wanted, or if this is a bug.

**Comment by CodeIngL** [comment]
请看BrokerData应该可以非常简单理解设计。 @superheizai

**Comment by xiangwangcheng** [comment]
This is an interesting issue. I suppose we need more discussion on it.
Since we use `brokerName `as the key of `brokerAddrTable`:
`private final HashMap<String/* brokerName */, BrokerData> brokerAddrTable;`
if two clusters have brokers with the same brokerName, when broker registers itself to nameserver, it will overwrite previous one and the previous one will overwrite it again by next registration. So the `brokerAddrTable `of namesever is uncertain and that is the reason the topic was created onto the cluster you didn't want.
IMO, the questions @superheizai raised MAY need to be enhanced though we can avoid it by setting totally different brokerNames for different clusters like below:
1.
brokerClusterName=DefaultCluster
brokerName=broker-a
2.
brokerClusterName=DefaultCluster
brokerName=broker-b
3.
brokerClusterName=DefaultCluster1
brokerName=broker-c
4.
brokerClusterName=DefaultCluster1
brokerName=broker-d

@zongtanghu @duhenglucky What do u think?
