### ISSUE TITLE
Bug in select MessageQueue

### ISSUE THREAD

**Issue by ShadowySpirits** [apache/rocketmq#1576]
When SendLatencyFaultEnable is enabled and the currently selection is available, you need to make sure that the currently selected broker is not the last selected.
But this judgment is wrong for now:
```java
// MQFaultStrategy#selectOneMessageQueue
MessageQueue mq = tpInfo.getMessageQueueList().get(pos);
if (latencyFaultTolerance.isAvailable(mq.getBrokerName())) {
    // this judgment shuold be change to if(!mq.getBrokerName().equals(lastBrokerName))
    if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))
        return mq;
}
```

**Comment by duhenglucky** [comment]
@ShadowySpirits @MountainOne IMHO, there's no issue to select one MQ with the current strategy.
On the one hand, RocketMQ will replace the target MQ to avoid load imbalance. On the other hand, once the latencyFaultTolerance.isAvailable() method returns true, it means the current broker is not isolated.

**Comment by ShadowySpirits** [comment]
@duhenglucky In my opinion, lastBrokerName represents the broker that should be avoided. But in the current logic is the broker that should be selected.

**Comment by ShadowySpirits** [comment]
Is there a problem with my understanding? Please correct me.

**Comment by duhenglucky** [comment]
> @duhenglucky In my opinion, lastBrokerName represents the broker that should be avoided. But in the current logic is the broker that should be selected.

In my opinion, lastBrokerName(means last selected broker) whether should be isolated only depends on isAvailable() method,   instead of adding judgment logic elsewhere, if the broker is not isolated, messages should be sent to the broker directly. This will also make the load of each broker more balanced.

**Comment by MountainOne** [comment]
@duhenglucky 
>On the one hand, RocketMQ will replace the target MQ to avoid load imbalance. On the other hand, once the latencyFaultTolerance.isAvailable() method returns true, it means the current broker is not isolated.

I totally agree with you. When `latencyFaultTolerance.isAvailable()` returns true, the current broker is available. But the problem is the following jugment `if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))`. When `lastBrokerName` is not null, it indicates that some exception has occured and program entered the retry logic. 
**The broker corresponding to lastBrokerName is already unavailable.** So `mq.getBrokerName().equals(lastBrokerName)` will definitely return false, result in no MQ will be chosen. Program Will automatically enter the following logic to randomly select the broker, MQFaultStrategy is not working.

**Comment by MountainOne** [comment]
Give an extreme example, the broker corresponding to `lastBrokerName` has been down, but the decision logic at this time still has to choose MQ on the broker, which is unacceptable.

**Comment by duhenglucky** [comment]
> Give an extreme example, the broker corresponding to `lastBrokerName` has been down, but the decision logic at this time still has to choose MQ on the broker, which is unacceptable.

if there's something wrong happened, this broker will be isolated by org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl#updateFaultItem(), this broker won't be avaliable.

**Comment by MountainOne** [comment]
Right, but the currently selected broker needs to be the same as the isolated broker, which is contradictory. 
```Java
 if (latencyFaultTolerance.isAvailable(mq.getBrokerName())) {
                        if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))
                            return mq;
                    }
```

**Comment by RongtongJin** [comment]
IMO, `if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))` this code line is redundant.

**Comment by ShadowySpirits** [comment]
> > @duhenglucky In my opinion, lastBrokerName represents the broker that should be avoided. But in the current logic is the broker that should be selected.
> 
> In my opinion, lastBrokerName(means last selected broker) whether should be isolated only depends on isAvailable() method, instead of adding judgment logic elsewhere, if the broker is not isolated, messages should be sent to the broker directly. This will also make the load of each broker more balanced.

According to your explanation, I submitted pr #1607 to delete the if statement.

**Comment by carlo-z** [comment]
![](https://imagehome.oss-cn-beijing.aliyuncs.com/20200109213255.png)

**Comment by ShannonDing** [comment]
link #1593
