### ISSUE TITLE
Retry doesn't work when sending msg in async mode(eg. when broker is down)

### ISSUE THREAD

**Issue by xiangwangcheng** [apache/rocketmq#1588]
**BUG REPORT**

1. Please describe the issue you observed:
When sending messages in async mode,  the retry times is set to be 1. The code is below:

![image](https://user-images.githubusercontent.com/8049014/68650700-9bf8e200-0560-11ea-94c0-a924e372b3b1.png)

And if the chosen broker is down at that moment, messages sending will fail with no retry.

- What did you do (The steps to reproduce)?
1. Send messages in async mode.
2. Pause the code after choosing a queue(Before really sending it)
3. shutdown the chosen broker
4. continue the code
- What did you expect to see?
The producer will retry another broker/queue.
- What did you see instead?
The producer throw exception without retrying.
2. Please tell us about your environment:
RMQ 4.6.0
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by xiangwangcheng** [comment]
Though we have the retry strategy at the callback part, a retry logic is still needed at the sending step in case of the situation of the broker-down.

**Comment by CodeIngL** [comment]
你代码在点点进去就看到另一个控制属性了 @xiangwangcheng

**Comment by xiangwangcheng** [comment]
> 你代码在点点进去就看到另一个控制属性了 @xiangwangcheng

Could you please show me where？

**Comment by MountainOne** [comment]
Message retry resynchronization in RocketMQ is implemented by calling the `sendKeynelImpl()` method in a for loop in `DefaultMQProducerImpl#sendDefaultImpl()`. The number of retries is obtained by `DefaultMQProducer#getRetryTimesWhenSendFailed()`.
Asynchronous message sending retry is implemented by `MQClientAPIImpl#onExceptionImpl()` recursively calling `MQClientAPIImpl#sendMessageAsync()` method in case of exception. The number of retries is obtained by `DefaultMQProducerImpl#.getRetryTimesWhenSendAsyncFailed()`. The default value is 2.
Therefore, if you do not set the number of asynchronous retries, you will retry at least 2 times, and the message will not be sent because there is no retry. Only the location of the asynchronous and synchronous send retry implementations is different, resulting in such a judgment.

在 RocketMQ 中同步的消息发送重试是通过`DefaultMQProducerImpl#sendDefaultImpl()`中的 for 循环，循环调用`sendKeynelImpl()`方法实现的。重试次数由`DefaultMQProducer#getRetryTimesWhenSendFailed()`获得。
而异步的消息发送重试是在出现异常的情况下，由`MQClientAPIImpl#onExceptionImpl()`递归调用`MQClientAPIImpl#sendMessageAsync()`方法实现的。重试次数由`DefaultMQProducerImpl#.getRetryTimesWhenSendAsyncFailed()`获得，缺省值为 2。
所以在不设置异步重试次数的情况下，也会至少重试 2 次，不会因为没有重试而导致消息发送失败。只是异步和同步发送重试实现的位置不一样，导致产生了这样判断。

**Comment by xiangwangcheng** [comment]
@MountainOne  I don't know if I have made myself clear or not.... it's a little bit complicated. @duhengforever @zongtanghu What do u guys think?

**Comment by duhenglucky** [comment]
@xiangwangcheng producer won't retry if there's a response returned, 
![image](https://user-images.githubusercontent.com/7938968/69041360-589fe700-0a2a-11ea-88b5-cc162d87d43a.png)
and will retry when the response is null.

**Comment by MountainOne** [comment]
@xiangwangcheng 
I fully understand what you mean.
But the callback function passed to `remotingClient.invokeAsync` will always be called, not only when the message is sent successfully. The callback function that you said is only called when the message is sent successfully should be the parameter `sendCallback` passed to `MQClientAPIImpl#sendMessageAsync`.
When the broker has gone down, the message sent will not be returned. `producer` will compare with the `timeoutMillis` according to the time the message has been sent. If it is greater than that, the message will be sent timeout. Set the send status of `responseFuture` to false and execute the `InvokeCallback` callback function passed in `remotingClient.invokeAsync()`. Regardless of whether the message was sent successfully or not, `InvokerCallback()` will be executed. Then, based on the returned response, if response returns and no exception occurs, it will not be retried; if it is null or an exception occurs, it will be retried.
The specific async communication logic can refer to `NettyRemotingClient#invokeAsync` and `NettyRemotingAbstract#invokeAsyncImpl` in the remoting module. Here is a list of key codes.

我完全明白您的意思。
但传给`remotingClient.invokeAsync`的回调函数总是会被调用的，不仅仅是在消息发送成功的时候。您所说的在只有在消息发送成功时才调用的回调函数应该是传给`MQClientAPIImpl#sendMessageAsync`的参数`sendCallback`。
当 broker 已经宕机时，发送的消息将无法返回。`producer`会根据消息已经发出的时间与`timeoutMillis`比较，大于则判断消息发送超时。将`responseFuture`的发送状态设置为 false 并执行`remotingClient.invokeAsync()`中传入的`InvokeCallback`回调函数。不管消息发送成功与否，`InvokerCallback()`都会执行。然后根据返回的 response 判断，如果 response 返回了且没有出现异常，就不会重试；如果为 null 或者出现异常，就会进行重试。
具体的异步通信逻辑可以参考 remoting 模块中的`NettyRemotingClient#invokeAsync`和`NettyRemotingAbstract#invokeAsyncImpl`。这里列一下关键代码，在`NettyRemotingAbstract#invokeAsyncImpl`中。
```Java
channel.writeAndFlush(request).addListener(new ChannelFutureListener() {
    @Override
    public void operationComplete(ChannelFuture f) throws Exception {
        if (f.isSuccess()) {
            responseFuture.setSendRequestOK(true);
            return;
        }
        requestFail(opaque);
        log.warn("send a request command to channel <{}> failed.", RemotingHelper.parseChannelRemoteAddr(channel));
    }
});
```

**Comment by xiangwangcheng** [comment]
@duhenglucky @MountainOne 
Sorry, seems I still haven't made myself clear.
I mean until one message queue is selected, everything is fine.
![image](https://user-images.githubusercontent.com/8049014/69128652-c0683780-0ae7-11ea-9650-7a612bdf9a06.png)

And after that(I set a breakpoint here),  I shut down the broker that the selected queue is running on.
The producer fails here（channel is null and `this.invokeAsyncImpl` won't be invoked）：
![image](https://user-images.githubusercontent.com/8049014/69128914-42586080-0ae8-11ea-8b61-6b5832be7511.png)

And InvokeCallback won't be invoked.
![image](https://user-images.githubusercontent.com/8049014/69129266-fb1e9f80-0ae8-11ea-99e0-052acc60beef.png)
And no retry logic for situations like that.

**Comment by MountainOne** [comment]
I understand now, thank you for your tips. In the case of a broker downtime, `NettyRemotingAbstract#invokeAsyncImpl` will not be executed and the retry logic will not be executed.
So we need to execute the retry logic before throwing the exception, or the message will be lost.

**Comment by xiangwangcheng** [comment]
I think reuse the for-loop retry logic of sending messages in sync mode is also OK.
![image](https://user-images.githubusercontent.com/8049014/69225381-3be5e980-0bb9-11ea-83d8-5da7b21a55a2.png)
`int timesTotal = communicationMode != CommunicationMode.ONEWAY ? 1 + this.defaultMQProducer.getRetryTimesWhenSendFailed() : 1;`

**Comment by MountainOne** [comment]
If you modify it as you said, after the message is sent asynchronously, regardless of the result , the message will be resent in the for loop immediately, causing the message to be sent repeatedly. If the blocking waits during the sending process, it does not reflect the advantage of asynchronous sending, which affects performance.
So I think the retry logic for asynchronous sent should still be in the callback function. You can consider canceling ` if (channel != null && channel.isActive())` and passing the logic that handle the exception to the callback function (which is actually done, such as `onExceptionImpl()`), so that every asynchronous call will be Triggered the callback function. But this solution is not elegant enough to directly modify the function of the remoting module, I am wondering if there is a better solution.

**Comment by xiangwangcheng** [comment]
No, if no exception is thrown during the sending process, the message will not be sent again.
```                      
switch (communicationMode) {
                            case ASYNC:
                                return null;
                            case ONEWAY:
                                return null;
                            case SYNC:
                                if (sendResult.getSendStatus() != SendStatus.SEND_OK) {
                                    if (this.defaultMQProducer.isRetryAnotherBrokerWhenNotStoreOK()) {
                                        continue;
                                    }
                                }

                                return sendResult;
                            default:
                                break;
```

**Comment by MountainOne** [comment]
You are right, I am not thinking about it. This is a viable solution.

**Comment by gaoyf** [comment]
同步发送，当broker无响应时，照样不会重试，可以参考[分析](https://blog.csdn.net/a417930422/article/details/103489927)。

**Comment by RongtongJin** [comment]
@xiangwangcheng +1, I think you are right.
