### ISSUE TITLE
question about ReferenceResource#hold

### ISSUE THREAD

**Issue by rushsky518** [apache/rocketmq#1780]
````java
    protected final AtomicLong refCount = new AtomicLong(1);
    public synchronized boolean hold() {
        if (this.isAvailable()) {
            if (this.refCount.getAndIncrement() > 0) {
                return true;
            } else {
                this.refCount.getAndDecrement();
            }
        }

        return false;
    }
````
refCount is already AtomicLong type, is it necessary to put `hold` method in a synchronized block

**Comment by RongtongJin** [comment]
IMO, it is neccessary to add `synchronized`, hold method must be mutually exclusive with the synchronized block below. Otherwise, it is possible that hold returns true and cleanup success.
https://github.com/apache/rocketmq/blob/73bb4b402a5da02faf9feded8f4d79dd1ba88348/store/src/main/java/org/apache/rocketmq/store/ReferenceResource.java#L56-L65
In addition, issue is for bug report and feature request, so welcome to ask question on [mail list](http://rocketmq.apache.org/about/contact/).
