### ISSUE TITLE
support  any delay for producer

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq#1832]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Now, rocketmq just support fixed delay message instead of any delay, which is not convenience for users. somtimes, we want to send message with any delay time: 1s, 2s and so on

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by 2259289435** [comment]
这个特性通过我通过在客户端加hook实现过，已经在生产环境运行了两年，想请教下你的实现方案



2259289435@qq.com
 
From: xujianhai666
Date: 2020-03-10 12:02
To: apache/rocketmq
CC: Subscribed
Subject: [apache/rocketmq] support any delay instead of fixed delay (#1832)
FEATURE REQUEST
Please describe the feature you are requesting.
Now, rocketmq just support fixed delay message instead of any delay, which is not convenience for users. somtimes, we want to send message with any delay time: 1s, 2s and so on
Provide any additional detail on your proposed use case for this feature.
Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:
sub-task1-issue-number: sub-task1 description here,
sub-task2-issue-number: sub-task2 description here,
...

**Comment by duhenglucky** [comment]
@xujianhai666 It is recommended to write a RIP first and then discuss it in the dev mailing list(dev@rocketmq.apache.org),  because it is a new feature that is widely concerned by the community

**Comment by 2259289435** [comment]
#1882 Please review
