### ISSUE TITLE
consumer queue of deleted topic is recovered on DefaultMessageStore#start

### ISSUE THREAD

**Issue by xujianhai666** [apache/rocketmq#1852]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
producer messages to commitLog and then delete topic, those messages has been dispatched to consumer queue，we delete consumer queue for safe. But when reboot broker, consume queue of the topic rebuilt again. 

- What did you expect to see?
consumer queue should not been built

- What did you see instead?
cosumer queue has been built 

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by imaffe** [comment]
yeah this make sense. Because when we delete a topic we don't delete the entries in the CommitLog, and the ReputMessageService will catch up from CommitLog.

In `doReput()` I didn't see the logic that checks if a CommitLog entry belongs to an existing topic. We might need to validate each CommitLog entry. 

I will look deeper into this issue, I'm reading source code recently so maybe I can help with it a bit.

**Comment by imaffe** [comment]
CommitLog#recoverAbnormally (deprecated) and DefaultMessageStore#doReput() used `doDispatch()`. We will do filter to filter out deleted topic message. Problem is when do we filter.

Do we put the filter in `doReput()` or put the filter in dispatcher implementation like `CommitLogDispatcherBuildConsumeQueue`. I think the later might be better.

**Comment by imaffe** [comment]
After I digged deeper into this problem, I found it rather hard to solve given we don't currently have reference topicManager in DefaultMessageStore.

To know which topics are currently not deleted in DefaultMessageStore, we cannot rely on it's `consumeQueueTable` because `consumeQueueTable` itself is constructed using commitLog(which contains entries that belong to a deleted topic)

In order to know if an entry in the commitLog belongs to a deleted topic, we have to query topicConfigManager, )but this would be a very big change as we introduced a dependency in broker level, which complicates the synchronization schema as well).

The problem is we can't selectively delete an entry in commitLog (unless they expires themselves), and upon restart the async CQ building process will always try to create a CQ entry for each entry in the commitLog. 

Seems like not introducing TopicConfigManager in the DefaultMessageStore would be a better choice if we can prove that keeping the consumeQueue for a deleted topic would not hurt safety. ()

Since consumers interacts directly with consume queues, it might be not safe in this case (as consume queue keeps the deleted topic information even the topic is not in TopicConfigManager). However I didn't verify this in the source code.


This exposes another problem. We are using topic Names instead of topicId as unique identifiers for a given topic, we cannot distinguish between a deleted topic and a new topic with a same name. For example, we deleted a topic "user_info" for application A, and we create a new "user_info" for topic B, they are not relevant but consumers can consume messages from older topic. We can avoid this by persuade users don't do so but these kinds of vulnerabilities would still exist. Since using one commitLog for all topics is the core feature of RocketMQ, choices we can make are very limited.

Will be so happy to see different opinions~~
