### ISSUE TITLE
Rocketmq heavily use NetworkInterface to get ip which is not recommended use in kubernates

### ISSUE THREAD

**Issue by YJFinBJ** [apache/rocketmq#1877]
rocketmq use NetworkInterface.getNetworkInterfaces() to getIp in many places, for example,  in  brokerlive cache, in store msg used as msg tag, etc.  As Cloud Native standard and kubernates is popular more and more，in which “ip” is not recommended use, while dns is the mainstream. So,
why rocketmq not decouple these "ip"  hard coded by NetworkInterface.getNetworkInterfaces(),other than make it configurable(ip or dns or any other form),  if possible.

**Comment by RongtongJin** [comment]
Good suggestion. RocketMQ is embracing cloud native, as you said, there are some issues at present, so PRs are welcomed to solve these issues.

**Comment by YJFinBJ** [comment]
since ip is marked as a tag for broker, and in cloud native, in k8s ,broker usually is set by statefulset, which we can use name+namespace as the unique tag, just like xx-xx-0-ns1, yy-yy-0-ns2. so we can configure it in our own broker statefulset, and that's the unique tag in k8s just as the "ip" in vm or node

**Comment by duhenglucky** [comment]
@YJFinBJ good suggestions, but IP is used throughout RocketMQ as a unique identifier, including client differentiation (this is reflected in many issues), message storage formats(IPv4&IPv6), etc. This does cause a lot of issues in the container environment, so there is very much of the work that needs to be done, such as the compatibility of the non-k8s environment that also needs to be considered. 

This change seems to be relatively large, so could you provide a more detailed design first so that more users from the community can participate?

**Comment by YJFinBJ** [comment]
about compatibility of non-k8s environment , I think make it configurable can resolve，default non-k8s support。

But just as mentioned, this does a really large work,  detailed design and also enough test needed, I think

**Comment by RongtongJin** [comment]
Hi @YJFinBJ YJ you can submit a [RIP](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal) if you have enough time to slove this issue. I am willing to be a shepherd for the RIP and solve this issue with you.
