### ISSUE TITLE
CONSUME_FROM_FIRST_OFFSET not working

### ISSUE THREAD

**Issue by GauravVect** [apache/rocketmq#2311]
I am using the cpp client of rocketMQ.In the cpp client there are examples in the example directory.I tried running the example OrderlyPushConsumer.cpp with consumer.setConsumeFromWhere(CONSUME_FROM_FIRST_OFFSET) and compiled the program.

gcc -I/home/gaurav/rocketmq-client-cpp-2.1.0/include/ -o test OrderlyPushConsumer.cpp -lrocketmq -lpthread -lz -ldl -lrt -lstdc++ -std=c++11.

Then I ran the test executable 
./test -n "10.22.7.89:9876" -g "VGroup" -t "PhaniRanjan" -m 1 -T 0 -c "Hello7 "

Then the message coming in messageQueue in  MyMsgListener::consumeMessage is Hello7 

But when i ran the test executable another time 
./test -n "10.22.7.89:9876" -g "VGroup" -t "PhaniRanjan" -m 1 -T 0 -c "Hello8 "
Only the message coming in messageQueue in MyMsgListener::consumeMessage is Hello8.

But Ideally it should have come as Hello7 followed by Hello8 which is not the case.
Can someone please explain what is happening.

**Comment by Jaskey** [comment]
You are using the same consumer group, so the consumer offset has already been logged in the broker, which when the consumer restart, it should consume message by the last offset. 

In a word, CONSUME_FROM will only happens when you change your consumer group name or a brand new consumer group starts.

**Comment by GauravVect** [comment]
Hi,
Thanks for the clarification.
