### ISSUE TITLE
SpringBoot 整合RocketMQ和Dubbo以后启动报错

### ISSUE THREAD

**Issue by fireshow** [apache/rocketmq#2327]
报错内容：
`2020-09-29 17:27:15.934 ERROR 7076 --- [enderExecutor_3] c.a.c.s.b.r.i.RocketMQMessageHandler     : RocketMQ Message hasn't been sent. Caused by No route info of this topic, dubboProtocolConfigSupplier-out-0
See http://rocketmq.apache.org/docs/faq/ for further details.`
`    <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-dubbo</artifactId>
        </dependency>
     <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-rocketmq</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.rocketmq</groupId>
                    <artifactId>rocketmq-spring-boot</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot</artifactId>
            <version>2.0.3</version>
        </dependency>
`

**Comment by xuwd** [comment]
你好

**Comment by JackGirl** [comment]
- - 是的，刚遇到

**Comment by duhenglucky** [comment]
> * * 是的，刚遇到

没有创建对应的topic，而且没有打开自动创建，在broker.conf 中，设置autoCreateTopicEnable=true，生产环节建议关闭，手工创建

**Comment by JackGirl** [comment]
> > * * 是的，刚遇到
> 
> 没有创建对应的主题，也没有打开自动在broker.中，设置autoCreateEnable=true，生产概念关闭，手工创建

我知道是没有topic  主要是不知道为啥整合dubbo后就有依赖这个topic  dubbo依赖里面也没有rocketmq啊

**Comment by geliyang99** [comment]
> 

你解决没有啊，我也遇到了，莫名其妙啊

**Comment by geliyang99** [comment]
> > > * * 是的，刚遇到
> > 
> > 
> > 没有创建对应的主题，也没有打开自动在broker.中，设置autoCreateEnable=true，生产概念关闭，手工创建
> 
> 我知道是没有topic 主要是不知道为啥整合dubbo后就有依赖这个topic dubbo依赖里面也没有rocketmq啊

你解决没有啊，我也遇到了

**Comment by DISSIDIA-986** [comment]
I used "Aliyun Java Initializr " to create a new project, with 
spring-boot-dependencies.version=2.3.7.RELEASE, 
spring-cloud-alibaba-dependencies.version=2.2.2.RELEASE, 
rocketmq-spring-boot-starter.version=2.0.2
dubbo-spring-boot-starter.version=2.7.8
then with start error:
[2022-03-03T19:54:54.943+0800] [ERROR] [RocketMQMessageHandler.java:220] [AsyncSenderExecutor_1] [[RocketMQ Message hasn't been sent. Caused by No route info of this topic, dubboProtocolConfigSupplier-out-0
See http://rocketmq.apache.org/docs/faq/ for further details.]]
