### ISSUE TITLE
如何实现消息在生产环境和灰度环境的隔离

### ISSUE THREAD

**Issue by WuJingLearn** [apache/rocketmq#2599]
How to achieve message isolation in production and grayscale environments

**Comment by Jaskey** [comment]
Different command will have their totally own different topology, so it is hard to give a answer to you since you only provide so little input.

While you can try this:

1. use two totolly different environments with different rocketmq broker cluster, when you need to send to gray env, register the grays' name server, when you needs prod env, register the prov's.
2. use the some rocketmq broker clusters, while give a env flag for every topics like: prod_xxxx, gray_xxx, and your client uses the topic accordingly.
