### ISSUE TITLE
Out of memory error when dledger is used

### ISSUE THREAD

**Issue by LuciferInLove** [apache/rocketmq#2859]
Hello. We had the rocketmq cluster installed with master-slave architecture, and then we moved it to the new dledger architecture. Brokers are running on small ec2 instances with such java options:

```
-Xms128m -Xmx128m -Xmn128m -XX:G1HeapRegionSize=1m -XX:MaxDirectMemorySize=256m
```

When we've used the master-slave architecture, everything worked correctly, but when we switched to the dledger architecture, we started getting Out of memory errors. We see many threads that allocate 4mb buffer. Is it the right behavior?

The log file with errors is attached.
[hs_err_pid_1.log](https://github.com/apache/rocketmq/files/6433664/hs_err_pid_1.log)

**Comment by panzhi33** [comment]
I think it has nothing to do with the architecture mode, mainly due to insufficient memory。as you can see from the log you gave, the thread that caused the OutOfMemory exception is sendmessage, and there is no change in the memory before and after gc.
![image](https://user-images.githubusercontent.com/29321745/117390132-2cc73880-af20-11eb-88a4-50e023dcc1b6.png)
![image](https://user-images.githubusercontent.com/29321745/117390172-3f417200-af20-11eb-8914-8b01a1b2b1c9.png)

**Comment by LuciferInLove** [comment]
In the dump, I also see sendmessage threads. I tried to increase memory on virtual machines drastically, and that didn't help - memory always runs out when dledger is enabled. When I don't use dledger, I don't have any OutOfMemory errors under the same load even with a small amount of memory.

**Comment by LuciferInLove** [comment]
Sorry. After updating to 4.8.0, the problem is not reproducible.
