### ISSUE TITLE
shutdown gracefully bug

### ISSUE THREAD

**Issue by Black-Mamba24** [apache/rocketmq#313]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do 
    shutdown broker gracefully, using wipeWritePerm command. after running wipeWritePerm the perm of topics on this broker become 4, but before shutdown broker, I change my mind, do not shutdown. but perms are still 4, I runned updateTopicPerm command, or operate on console(apache opensource), but this operation update all the topic perms to 6. 
    Two reason:
    1) wipeWritePerm only update perm on namesrv
    2) dataVersion only relay on broker not topic, one of the topics perm changed, it will change the dataVersion of broker, and update all topic perms.

- What did you expect to see?
    update topic perm one by one

- What did you see instead?
    already say

2. Please tell us about your environment:
    it is nothing about env

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
    no more

**Comment by lizhanhui** [comment]
Instead of change all topic permission on the broker which is about to be shut down, we suggest changing the permission of the broker itself. That is, `updateBrokerConfig -b IP:port -k brokerPermission -v 4`. In case you changed your mind, you are good to revert broker permission to 6 without affecting individual permission of each single topic.

**Comment by lizhanhui** [comment]
I'll cose this ticket for now and you may reopen it in case it does not solve your problem in any way, please do not hesitate to reopen it.

**Comment by Black-Mamba24** [comment]
@lizhanhui  thx, it's really helpful
