### ISSUE TITLE
The RocketMQ server is incompatible with the Apache Skywalking service

### ISSUE THREAD

**Issue by liwei0423** [apache/rocketmq#3331]
In the company's test environment, the RocketMQ consumer's tag was tampered with by Skywalking

The producer sends the tag as exam, and the consumer receives the topic, which reads the tag as examsw8-x^A0, When Apache Walking is shut down, RocketMQ returns to normal and Tag returns to exam

RocketMQ server 4.9.1
RocketMQ client 4.9.1
Apache Skywalking 8.1

**Comment by RongtongJin** [comment]
So this is the issue of skywalking?

**Comment by vongosling** [comment]
@wu-sheng Could you please look at it, Maybe it's a compatibility issue:-0

**Comment by wu-sheng** [comment]
Hi, I am out of office this week. I may be able to check on weekend.

**Comment by wu-sheng** [comment]
I just checked the codes, SkyWalking's plugin for RocketMQ v4 just uses headers to propagate headers at the producer.

https://github.com/apache/skywalking-java/blob/61892085f95512df5bd8c7c7b67394b40b9f7a1f/apm-sniffer/apm-sdk-plugin/rocketMQ-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/rocketMQ/v4/MessageSendInterceptor.java#L65-L77

Is there anything related to your context?

**Comment by wu-sheng** [comment]
FYI, header of sw8-x is following this definition, https://skywalking.apache.org/docs/main/v8.7.0/en/protocols/skywalking-cross-process-propagation-headers-protocol-v3/#extension-header-item

It should have 0- prefix as value, which means this trace should be analyzed to generate metrics and topology.

**Comment by HScarb** [comment]
After debugging rocketmq 4.9.1 and skywalking 8.x, I found out the reason.

It is because this PR of rocketmq https://github.com/apache/rocketmq/pull/2961

https://github.com/apache/rocketmq/blob/fb8bc64e2a2551e76da24cb6af0fb3e5f986f8b3/common/src/main/java/org/apache/rocketmq/common/message/MessageDecoder.java#L442-L444

here add some new codes to delete the last `PROPERTY_SEPARATOR` of `properties`, however skywalking interceptor not expecting it.

I'll post a PR for skywalking soon to solve this issue

**Comment by wu-sheng** [comment]
This should have been fixed

**Comment by drpmma** [comment]
close the
