### ISSUE TITLE
the client consumers in docker enviroment of two machines leads the same clientid on the consuming side because of the same returning ip 

### ISSUE THREAD

**Issue by liaoliang** [apache/rocketmq#3480]
the client consumers in two machines leads the same clientid on the consuming side because of the same returning ip

**Comment by Git-Yang** [comment]
This problem can be solved by setting a different instanceName for the consumer instance.

**Comment by liaoliang** [comment]
> This problem can be solved by setting a different instanceName for the consumer instance.

i want to know whether two ip is the same in docker overlay mode of two machines

**Comment by duhenglucky** [comment]
> i want to know whether two ip is the same in docker overlay mode of two machines

Under HOST networking mode, all dockers managed by Rancher are with the same docker0 IP, which is 172.17.0.1. Thus, RemotingUtil.getLocalAddress() always returns "172.17.0.1" for those dockers, which leads to a collision between consumers with the same PID, if using default "IP@pid" clientId.

But it's recommended you bump up your client version to the lastest, because the instanceName change to a new one with nanoTime to prevent this collision:
` if (this.instanceName.equals("DEFAULT")) {
            this.instanceName = UtilAll.getPid() + "#" + System.nanoTime();
   }`
