### ISSUE TITLE
The client provides support for JDK 1.6

### ISSUE THREAD

**Issue by duhenglucky** [apache/rocketmq#3684]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
There are still a lot of users using the JDK 1.6, especially in traditional industries, they hope that the client can provide compatibility with JDK 1.6.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by ferrirW** [comment]
There are some risk with still using Jdk 1.6 because it no longer update since 2018.

In order for users to use rocketmq more safely and with high performance, maybe we should consider given an JDK upgrade schedule, such as switching to JDK 8 after 5.0, and upgrading to JDK17 after 6.0. 

Then, users still using jdk 1.6 can use a relatively low version of the client such as 4.9.4, while newer users can use the latest version and features.

**Comment by caigy** [comment]
@ferrirW After 5.0, the client requires JDK version 8.0 or above: https://rocketmq.apache.org/dowloading/releases/
