### ISSUE TITLE
[DISCUSS] Add a system property to override Runtime.getRuntime().availableProcessors()

### ISSUE THREAD

**Issue by gogodjzhu** [apache/rocketmq#3719]
I deploy rocketmq in docker environment. While there are some properties which take the number of runtime processors as default. It causes the jvm to start up with the physical setting which is not suitable for my virtual host.
 
I do know there are some ways to correct this, such as:
1. add `-XX:ActiveProcessorCount=count` to start up. But only after jdk8u191
2. upgrade jdk to jdk 11.
However, it is hard to push such an upgrade in a big company like us. 

Or 
3. do some code to change all the properties that refer to runtime.
It's too much work to do so and may not be suitable for different versions.

So I suggest adding an optional system property to accomplish this. 

Thx.
Best regards.

**Comment by Git-Yang** [comment]
I think Runtime.getRuntime().availableProcessors() can be used as default, and supporting parameter configuration should solve your problem.

**Comment by Kvicii** [comment]
@Git-Yang well, I think the configuration class parameters should be more concise and concise, configuration parameters in code now appear in many places, Of course this is just my personal opinion😀

**Comment by caigy** [comment]
As this problem occurs in docker environment, I think it would be more appropriate to upgrade the JDK version in container, other than change codes in application level. Because such uncompleted support to container in JDK does not only affect `Runtime.getRuntime().availableProcessors()`, but also ParallelGCThreads, CICompilerCount, etc.  

BTW, it seems that this problem has resolved after jdk8u131: https://blogs.oracle.com/java/post/java-se-support-for-docker-cpu-and-memory-limits
