### ISSUE TITLE
[Feature Request] Support New Batch Producer API that allow multiple topics in one Batch

### ISSUE THREAD

**Issue by Zanglei06** [apache/rocketmq#3806]
The current batch producer api requires that all messages in the batch belongs to one topic. However, sometimes user want to send batch message that belongs to multiple topics.  It would be good to provide such multi-batch producer api.

**Comment by duhenglucky** [comment]
@Zanglei06 Would you like to review this PR, these two PRs can be better combined.

**Comment by guyinyou** [comment]
The old Broker side can send multiple topics in batches, because the Broker unpacks each Message and redelivers it after receiving the MessageBatch. The new Broker side enhances the MessageBatch capability, but because it does not unpack specific Messages, it does not support batch sending of multiple topics.

**Comment by guyinyou** [comment]
Wecurrently plan to do a feature of sending multiple topics in one batch, but it may more like aggregation of multiple MessageBath requests in the remoting layer
