### ISSUE TITLE
Why transactional message can not send by using MessageQueueSelector?

### ISSUE THREAD

**Issue by smcdl** [apache/rocketmq#399]
Why transactional message can not send by using MessageQueueSelector?

**Comment by duhengforever** [comment]
@smcdl In order to simplify the transactional message process, we didn't provide a method to support both MessageQueueSelector and send transactional message, actually it can also be combined before send the prepare message，and if you interested in the issue, welcome to pull a request about it, we are glad to help you complete this new feature.
