### ISSUE TITLE
Is there a performance pressure test report between rocketmq and other mq. For example, Kafka

### ISSUE THREAD

**Issue by TsingLiang** [apache/rocketmq#4275]

**Comment by duhenglucky** [comment]
@TsingLiang It is difficult to give a more objective performance evaluation, because it involves different scenarios and different configurations, so there are two suggestions, one is to evaluate whether rocketmq meets the requirements for your own scenario, and secondly, if you have to do one for comparison, you can do some tests according to your scenarios. Tools are provided in [OpenMessaging](https://github.com/openmessaging/benchmark).
