### ISSUE TITLE
NettyEventExecutor .putNettyEvent is not thread safe

### ISSUE THREAD

**Issue by Justinwins** [apache/rocketmq#4533]
```
 class NettyEventExecutor extends ServiceThread {
        private final LinkedBlockingQueue<NettyEvent> eventQueue = new LinkedBlockingQueue<NettyEvent>();
        private final int maxSize = 10000;

        public void putNettyEvent(final NettyEvent event) {
            int currentSize = this.eventQueue.size();
            if (currentSize <= maxSize) {
                this.eventQueue.add(event);   // it's  not thread safe here . 
            } else {
                log.warn("event queue size [{}] over the limit [{}], so drop this event {}", currentSize, maxSize, event.toString());
            }
        }

```

**Comment by lizhiboo** [comment]
@Justinwins IllegalStateException("Queue full") will not be thrown if using offer method, and then, channel will not be closed although NettyEvent is lost. If the lost event is NettyEventType.CLOSE, still using this channel will make mistake.

**Comment by Oliverwqcwrw** [comment]
IMO, although it is thread unsafe, it will only have a few more events, and it does not seem to have a serious impact, WDYT?

**Comment by lizhanhui** [comment]
@Oliverwqcwrw The crux here is can we afford dropping events in case there are too many netty events... From design perspective, we should not drop events here, otherwise, we have to compensate logic by way to schedule scanning wherever relies on channel state...
This is why ClientHouseKeepingService has a scheduled thread: https://github.com/apache/rocketmq/blob/a62b70bc25423c1d7e18043e32af427d29ef9ac4/broker/src/main/java/org/apache/rocketmq/broker/client/ClientHousekeepingService.java#L43

Obviously, it is a trade-off...when there are a massive number of events to handle and the ChannelEventListener implementation cannot process them timely...drop those events and let the schedule scanning to maintain eventual consistency. 

To be honest, it's pretty error-prone when implementing new features that may rely on channel state. They are very likely to forget to implement the compensation logic. 

A better alternative is to ensure every netty event is handled.

**Comment by lizhanhui** [comment]
@lizhiboo
