### ISSUE TITLE
diskMaxUsedSpaceRatio had no effect.

### ISSUE THREAD

**Issue by lindow2009** [apache/rocketmq#4707]
set diskMaxUsedSpaceRatio=99 in broker.conf and properties，but it had no effect.

always has error。
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 14  DESC: service not available now. It may be caused by one of the following reasons: the broker's disk is full [CL:  0.92 CQ:  0.92 INDEX:  0.92], messages are put to the slave, message store has been shut down

how  to fix it?

**Comment by duhenglucky** [comment]
> 
It looks like there are two problems:
1. If you want to delete the old commitlog immediately, you can try to use _fileReservedTime_ and _diskMaxUsedSpaceRatio_  these wo parameters at the same time.
2. This error can be optimized, and sending a message to the slave broker will also generate this exception, would you like to submit a PR to polish it?

**Comment by WeiJiaYue** [comment]
Same problem here.Still not work after I tried `fileReservedTime ` and `diskMaxUsedSpaceRatio `  both

**Comment by duhenglucky** [comment]
> Same problem here.Still not work after I tried `fileReservedTime ` and `diskMaxUsedSpaceRatio ` both

Maybe you only have one commitlog in your store path. It is recommended to write more data, multiple commitlogs, and then set the values of these two parameters as small as possible, and then observe the effect. If it does not work, wish you can provide more detailed information. such as store.log

**Comment by WeiJiaYue** [comment]
**Problem**
* diskMaxUsedSpaceRatio had no effect.
* with error below
```
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 14 DESC: service not available now. It may be caused by one of the following reasons: the broker's disk is full [CL: 0.92 CQ: 0.92 INDEX: 0.92], messages are put to the slave, message store has been shut down
```

**How to solve**
* With -Drocketmq.broker.diskSpaceWarningLevelRatio instead of diskMaxUsedSpaceRatio

**New Question**
Finally, solved this problem after delving in source code.
In fact ,the parameter `diskMaxUsedSpaceRatio ` does not work, it can be solved by parameter `diskSpaceWarningLevelRatio` with -Drocketmq.broker.diskSpaceWarningLevelRatio

As the snippet below,the `diskMaxUsedSpaceRatio` seems to have no effect,Is it possible to be optimized here?
<img width="932" alt="image" src="https://user-images.githubusercontent.com/38973058/182155494-e82f1e48-71ff-40a0-af29-cc3a8336770c.png">

**Comment by WeiJiaYue** [comment]
> set diskMaxUsedSpaceRatio=99 in broker.conf and properties，but it had no effect.
> 
> always has error。 org.apache.rocketmq.client.exception.MQBrokerException: CODE: 14 DESC: service not available now. It may be caused by one of the following reasons: the broker's disk is full [CL: 0.92 CQ: 0.92 INDEX: 0.92], messages are put to the slave, message store has been shut down
> 
> how to fix it?

With -Drocketmq.broker.diskSpaceWarningLevelRatio instead of diskMaxUsedSpaceRatio
