### ISSUE TITLE
In HA mode, if you do not truncate consumerOffsetMap, it may cause a bug

### ISSUE THREAD

**Issue by fujian-zfj** [apache/rocketmq#4771]
**BUG REPORT**
![image](https://user-images.githubusercontent.com/10379042/182748195-a0174024-0a6e-49e4-b06a-00816157bbd8.png)
1.nodes in syncStatusSet  all not available.
2.enableElectUnCleanMaster = true, slave3 was chosen to be master.
3.slave4 tried to truncate commitLog.
4.slave4  was chosen to be master and continued to append new message to commitLog.
5.consumer started to consume message from consumerOffset.

**Comment by RongtongJin** [comment]
Good catch!  I think we'd better correct consumerOffset while truncating the commitlog. Could you submit a pull request to fix the issue?

**Comment by lizhanhui** [comment]
I believe this is a design flaw. Leader/master nodes shall **ONLY** replicate their WAL logs to their peers/slaves.  All activities, including updates of consume-offsets, should be reflected in the WAL log. Peer nodes and slaves restore state machines by replaying WAL.

The current implementation has more than one replication path, this is the root cause of the discrepancy.

**Comment by lizhimins** [comment]
We should avoid using EnableElectUncleanMaster.
