### ISSUE TITLE
isSpaceToDelete method is not robust enough when some config change

### ISSUE THREAD

**Issue by BiggerBrain** [apache/rocketmq#4803]
isSpaceToDelete method is not robust enough when some config change
![image](https://user-images.githubusercontent.com/17764158/183650226-9bb5d11b-a9be-4d65-92bf-defdb03f3417.png)

**Comment by vongosling** [comment]
Could you share your detailed analysis with us? We've always had respect for robust code and hope to keep improving:-)

**Comment by vintagewang** [comment]
> isSpaceToDelete method is not robust enough when some config change
> 
> ![image](https://user-images.githubusercontent.com/17764158/183650226-9bb5d11b-a9be-4d65-92bf-defdb03f3417.png)
> 
> 

You can find the earlier code in the commit records which has comments for each variable, then we can figure out the specific problems.

**Comment by guyinyou** [comment]
If diskspacewarninglevelratio is less than diskspaceclenforciblyratio, it will never go to the logic that
`if(minPhysicRatio > diskspaceclenforciblyratio)`

**Comment by lizhanhui** [comment]
@guyinyou By design, this is to define the reclamation policy of the default message store and kick off the reclaiming thread when free disk space is running low. The whole design is pretty similar to how [Linux manages memory](https://blogs.oracle.com/linux/post/anticipating-your-memory-needs)

With that said, we may have two improvements:
1. Watermarks measured in megabytes are better than the ratio. Image, if disks with a capacity of 100G expect a much more urgent action than those with a capacity of 4T if both of them have 15% disks free;
2.  Free disk watermarks of min, low, and high (in Linux kernel terms) shall be validated before getting applied, where min <= low <= high.
