### ISSUE TITLE
[RIP-46] Rocketmq producer side supports idempotency

### ISSUE THREAD

**Issue by kaori-seasons** [apache/rocketmq#4933]
In the current process of rocketmq producing messages, there is uncertainty in the network call itself, that is, the so-called processing state, so there will be repeated situations. This problem is also encountered by many other MQ products. The usual method is to require the consumer to deduplicate when consuming messages. The idempotent basis should be generated by the message producer. When sending a message, we can pass the key of the message. Set the id, the corresponding API is org.apache.rocketmq.common.message.setKeys(String keys) The logic of this part should be optimized by the producer

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by complone** [comment]
@duhenglucky please assign to me

**Comment by zhouxinyu** [comment]
> @duhenglucky please assign to me

It's a big feature, do you have any plan or proposal if you want to pick up this issue?

**Comment by complone** [comment]
The details are still being sorted out and other Rocketmq issues are still in progress

**Comment by duhenglucky** [comment]
@complone It's a great improvement proposal. hope to see your detailed design. we'd better discuss it in the community first, @ltamber and me are willing to join in and complete this feature together.

**Comment by complone** [comment]
The real existence of this function I think I am referring to [kafka's inbox](https://www.archive.link/dig/detail/1652381596718757 ), etc. to send the rId that implements mq。

**Comment by azhsmesos** [comment]
> @complone It's a great improvement proposal. hope to see your detailed design. we'd better discuss it in the community with [RIP](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal) first, @ltamber and I are willing to join in and complete this feature together.

May I ask where is the corresponding RIP discussed? Can you give me a link

**Comment by complone** [comment]
> 阿

@azhsmesos I think I need to investigate the implementation mechanism of rocketmq transactions first. I am currently sorting out the related method call timings of kafka and rocketmq transactions. After sorting out, I will establish a RIP discussion

**Comment by complone** [comment]
Hello everyone, the problems we need to solve at this stage are:
In order to improve the accuracy of data and ensure the consistency between the source and the target in the end-to-end transmission process, it is necessary to do idempotent at the producer or consumer
However, if consumers cannot connect to the nameserver to obtain partition information temporarily due to network jitter, they need to implement idempotent mechanism in the producer
For this reason, our goal is to align the produerId and transactionId of kafka. There are three points to note at this stage by following the code
-  First, before sending data, you need to manually create a transaction coordinator to control the one to many relationship between PID and transcationId. To this end, you need to ensure that the consumption progress of offset is notified to the tc in a timely manner and that the messages of submitted but unsettled transactions will not be deleted by mistake during the simultaneous process of the scheduled deletion task
- Whether it is necessary to judge the progress of the current offset and the global PID visible transaction offset in PullLiteProductor in order to enable PID ->transactionid to achieve cross partition transaction consistency
- When downstream consumers consume, they need to ensure that messages marked as transactionId in the upstream market are perceived by downstream consumers

**Comment by complone** [comment]
see RIP-47 : https://docs.google.com/document/d/1nResLevPbeGmKwSQiId_jw0tfBhJtoPZTduOQL3qxNg/edit?usp=sharing
