### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by yushan-yaojin** [apache/rocketmq#5068]
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;

1、开发环境、测试环境、生产环境 都是jdk11
2、在开发环境、测试环境正常 ，在生产环境报以上错误
3、测试、生产 环境服务器均是 centos

**Comment by ShadowySpirits** [comment]
Please give more detailed information like exception stack.

**Comment by RongtongJin** [comment]
> java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
> 
> 1、开发环境、测试环境、生产环境 都是jdk11 2、在开发环境、测试环境正常 ，在生产环境报以上错误 3、测试、生产 环境服务器均是 centos

使用的rocketmq版本是什么

**Comment by aaron-ai** [comment]
This issue may be cause by cross-compilation, which is not supported with RocketMQ yet.

**Comment by caigy** [comment]
It occurs when building with JDK version >=9 and running on JDK8.
Ref: https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/

**Comment by aaron-ai** [comment]
We could consider to upgrade the JDK to 9+, which could use `--release` flag to support cross-compilation.

related link: https://openjdk.org/jeps/247

**Comment by yushan-yaojin** [comment]
> > java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
> > 1、开发环境、测试环境、生产环境 都是jdk11 2、在开发环境、测试环境正常 ，在生产环境报以上错误 3、测试、生产 环境服务器均是 centos
> 
> 使用的rocketmq版本是什么
   mq服务端版本是：4.9.4 
   springboot应用端的mq是：rocketmq-spring-boot-starter  2.2.1
   jdk版本都是：openjdk version "11.0.10"   

  错误在：org.apache.rocketmq.common.message.MessageExt.socketAddress2ByteBuffer ,第80行

**Comment by yushan-yaojin** [comment]
> Please give more detailed information like exception stack.
java.lang.NoSuchMethodError:java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;org.apache.rocketmq.common.message.MessageExt.socketAddress2ByteBuffer  ,line 80

Mq : 4.9.4
springboot app: rocketmq-spring-boot-starter 2.2.1
Jdk:  openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)


> It occurs when building with JDK version >=9 and running on JDK8. Ref: https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/
run on jdk11
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

**Comment by erghjmncq6643981** [comment]
我在使用rocketmq-client时也发现了这个问题，debug错误如下所示：
![image](https://user-images.githubusercontent.com/28293807/190585208-c07fd116-40a5-45f9-baad-1cc2fee5a539.png)
错误产生的原因是，由于rocketmq是在JDK17的环境中进行构建的：
![截屏2022-09-14 15 12 50](https://user-images.githubusercontent.com/28293807/190584711-589a3a62-467a-463f-bbcb-3b777d94b6f9.png)
解决方法：降低版本，或者自己在低版本jdk中构建
相关信息如下所示：
In Java 8, while calling flip() method of ByteBuffer class, since it has no implementation for this method, so it is actually calling the method from extended class, Buffer; which is returning Buffer object as below:

In Buffer class:

```
public final Buffer flip() {
    limit = position;
    position = 0;
    mark = -1;
    return this;
}
```
However, in Java 11, ByteBuffer class has implemented its own flip() method, and the returning object is changed from Buffer to ByteBuffer (This change should be started from Java 9):

In ByteBuffer class:

`ByteBuffer flip() {
    super.flip();
    return this;
}`

**Comment by samyScott** [comment]
pls assign to me

**Comment by aaron-ai** [comment]
@samyScott I have assigned it to you.
