### ISSUE TITLE
how to get message's body from messgeView

### ISSUE THREAD

**Issue by MumfordSons** [apache/rocketmq#5342]
messageView.getBody returns ByteBuffer object ，does it has graceful method to get messageBody？
![image](https://user-images.githubusercontent.com/45234194/196329537-6fc05f7b-de85-4e72-a547-7bddda14e828.png)

**Comment by aaron-ai** [comment]
@MumfordSons Thanks for your feedback! Actually message body in `messageView` is readonly, which means you could not get `byte[]` from `bytebuffer` directly because `byte[]` here is the underlying reference and it is not read only.

Just copy `byte[]` from `bytebuffer` If you still need to get `byte[]` from readonly bytebuffer. By the way, creating issues from [rocketmq-clients](https://github.com/apache/rocketmq-clients) could help it to attract more attention. 😊

**Comment by MumfordSons** [comment]
> @MumfordSons Thanks for your feedback! Actually message body in `messageView` is readonly, which means you could not get `byte[]` from `bytebuffer` directly because `byte[]` here is the underlying reference and it is not readonly.
> 
> Just copy `byte[]` from `bytebuffer` If you still need to get `byte[]` from readonly `bytebuffer`. By the way, creating issues from [rocketmq-clients](https://github.com/apache/rocketmq-clients) could help it to attract more attention. 😊
ok，thanks
