### ISSUE TITLE
Do producer‘s apis in rocketmq5 not support send with selector?

### ISSUE THREAD

**Issue by daigoopautoy** [apache/rocketmq#5496]
I use `org.apache.rocketmq.client.producer.DefaultMQProducer#send(org.apache.rocketmq.common.message.Message, org.apache.rocketmq.client.producer.MessageQueueSelector, java.lang.Object)` to send orderly msg in rocketmq4.x, which selector will select queue by msg's key, same key will direct to same MessageQueue.

But I cannot find  producer's apis can support I do same operation in rocketmq5. I only find rocketmq-proxy 
use `org.apache.rocketmq.proxy.grpc.v2.producer.SendMessageActivity.SendMessageQueueSelector` to select MessageQueue by msg's MessageGroup. If the msg have no MessageGroup, which means normal msg, rocketmq-proxy will select MessageQueue on Round-Robin.

Is this the design of rocketmq5? I hope rocketmq5 can be compatible for the orderly msg not strictly.

**Comment by aaron-ai** [comment]
Yes, it's by design.

In RocketMQ 5.x, you could use FIFO/orderly message by setting message group for each message you want to send. Here is the example: https://github.com/apache/rocketmq-clients/blob/master/java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerFifoMessageExample.java

**Comment by aaron-ai** [comment]
@daigoopautoy Well, actually we have not exposed queue semantic yet in RocketMQ 5.x, but it is in our roadmap.
