### ISSUE TITLE
[DISCUSS] [RIP-57]Optimize Building CommitLog

### ISSUE THREAD

**Issue by nowinkeyy** [apache/rocketmq#5529]
Hi, RocketMQ Community

Writing a message to the CommitLog file is a serial process (because a lock needs to be acquired before writing). When message production traffic is high, messages are written to CommitLog files too slowly, causing delays in ReputMessageService building ConsumeQueue, causing severe commit log scheduling delay warnings, and further delaying consumer consumption of messages.

We need to optimize the write process to be lock-free and write commitLog concurrently.

You can see more details in the documentation below
English version <https://yu7y22ce7k.feishu.cn/docx/doxcnkq0FHNr6yJng7LZp76Eo9g>
Chinese version <https://yu7y22ce7k.feishu.cn/docx/doxcnRF7e3vdg7A6wWlKBxOxIs5>

Please reply to this issue if you have any questions. 
Also can reply to https://lists.apache.org/thread/8x4p0gn5bdzdfcqz82k681th728xy98o.

Best Regards!

**Comment by shy-share** [comment]
I think this is feasible

**Comment by hzh0425** [comment]
Good job!

**Comment by lizhanhui** [comment]
@nowinkeyy The storage industry evolves rapidly with the continuously emerging medium, HDD, SSD, Optane SSD, Persistent Memory. So is the protocol, SCSI, SATA, NVMe... As the storage technique improves, the bottleneck changes and the software stack turns out to be the culprit one See https://atlarge-research.com/pdfs/2022-systor-apis.pdf

This impacts how we design software, especially when dealing with storage tier.

After investigating these techniques, I come about two approaches with their respective highlights and drawbacks
The first one is kind of classic, similar to how RocksDB writes its WAL file:

![opt_wal-RocksDB-Like drawio](https://user-images.githubusercontent.com/641819/202259176-80166b18-aa95-491b-b522-70233abfad79.png)

The second one is a modern solution, assuming a new underlying medium and storage software stack
![opt_wal-Run2Complete drawio](https://user-images.githubusercontent.com/641819/202259361-63c585dd-9696-4be9-89f9-d9f542fa39cf.png)

Let's compare these two with your proposed one before calling to vote.

**Comment by ShadowySpirits** [comment]
Using the spin lock instead of system semaphore will reduce the cost of system call but increase CPU usage. We should have more performance tests to support this proposal. And I am not sure that buffering messages in memory will improve throughput because buffer IO provided by OS already do this.

**Comment by nowinkeyy** [comment]
> Using the spin lock instead of system semaphore will reduce the cost of system call but increase CPU usage. We should have more performance tests to support this proposal. And I am not sure that buffering messages in memory will improve throughput because buffer IO provided by OS already do this.

Thank you for your reply! This proposal aims to resolve the issue of serial message write commitlog blocking, using buffers to support parallel message write and batch processing can improve throughput. The parallel buffer writing mode is cas, and whether to use spin lock or system semaphore needs to be considered.

**Comment by ShadowySpirits** [comment]
> This proposal aims to resolve the issue of serial message write commitlog blocking, using buffers to support parallel message write and batch processing can improve throughput

My point is we need proof to evaluate whether this optimization is necessary. Whether the current architecture can fill up the IO of SSD? How much performance improvement does the new solution have?
