### ISSUE TITLE
Io.netty.util.Recycler memory usage is too high

### ISSUE THREAD

**Issue by Rongze92** [apache/rocketmq#6050]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/100855894/218447868-bbe0fd31-f631-41ca-bf7a-c5cf7ef463b5.png">
官方说Netty4.1.74.Final解决了这个问题  rocketmq什么时候更新

**Comment by Oliverwqcwrw** [comment]
Can you send  the official article on this topic?

**Comment by Rongze92** [comment]
> Can you send the official article on this topic?

please follow this link :
https://www.cnblogs.com/binlovetech/archive/2022/07/06/16451821.html?share_token=D8F57C79-5313-4443-9B4B-253742A635E2&tt_from=copy_link&utm_source=copy_link&utm_medium=toutiao_ios&utm_campaign=client_share

**Comment by Oliverwqcwrw** [comment]
Thanks for your feeedback @Rongze92 ,

After reading this issue [netty #11864](https://github.com/netty/netty/issues/11864) I think the author wants to express that the problem of gc pressure is not the problem of memory leakage, because the container of the recovered object is a WeakReference

<img width="911" alt="image" src="https://user-images.githubusercontent.com/31796988/219248604-39388593-44d8-4b8b-b527-281c51d5fc41.png">

Please let me know if I am missing something.
