### ISSUE TITLE
how to do canary deployment with RMQ?

### ISSUE THREAD

**Issue by sagitchen** [apache/rocketmq#630]
Hi everyone, 

Is there any suggestion can share with me about canary deployment with RMQ? We have already deployed RMQ in our production env, basically we don't want to change existing topic or tags for messages and want to make sure only canary consumers will receive the new messages.

Thanks

**Comment by duhenglucky** [comment]
@sagitchen maybe you can implement your own rebalance method by implement this org.apache.rocketmq.client.consumer.AllocateMessageQueueStrategy interface to allocate the new message queue to the canary consumer.
And we recommend to subscribe and ask these question in our [mailing list](https://rocketmq.apache.org/about/contact/) because the issue only used for the bug report and feature request. but this issue also can be seemed like a feature request. Aha!

**Comment by sagitchen** [comment]
@duhengforever , thanks for your feedback. Actually I also have the same idea to implementation my own AllocateMessageQueueStrategy to select the canary queues. Also it seems we need to implement the MessageSelector based on the same selection algo to distinguish the canary producer. And we need to dynamically twist the ration of canary traffic to exiting production traffic. So this becomes complicated and I do implemented a POC to do that, but it seems not graceful enough. So I am wondering whether there is a existing solution with current RMQ release, unluckily it seems not :( .  I have to improve my solution now. But still thanks for you!

**Comment by mobaijaavaer** [comment]
Hello everyone, I have a solution for canary deployment of RocketMQ that I would like to share with you.

**Comment by mobaijaavaer** [comment]
https://blog.csdn.net/qq_35323137/article/details/140133376
@duhenglucky   @sagitchen
