### ISSUE TITLE
StoreCheckpoint setLogicsMsgTimestamp dont work right , may cause message loss 

### ISSUE THREAD

**Issue by Ah39** [apache/rocketmq#678]
**setLogicsMsgTimestamp  have the two place .
In the putMessagePositionInfoWrapper set .** 

https://github.com/apache/rocketmq/blob/f8a67adde7ce4c1cf6b8e7a0d1d9a1f1aaddbf30/store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java#L397-L402

**FlushConsumeQueueService do not  set the logicsMsgTimestamp right .**
https://github.com/apache/rocketmq/blob/f8a67adde7ce4c1cf6b8e7a0d1d9a1f1aaddbf30/store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java#L1655-L1680
**IndexService flush the  checkpoint , what if index flush the  logicsMsgTimestamp  , but  the consumer queue file dont flush success  when os down. 
so the message may loss**

https://github.com/apache/rocketmq/blob/2b692c912d18c0f9889fd73358581bcccf37bbbe/store/src/main/java/org/apache/rocketmq/store/index/IndexService.java#L359-L362

**if last consumer queue flush success ，logicsMsgTimestamp  is 11:14 
the new time is 
    physicMsgTimestamp  11:17
    logicsMsgTimestamp = 11:16
    indexMsgTimestamp = 11:16
when index file  flush  , but the 11:16 consumer queue file dont flush .
So may from 11:14 to 11:16 dispatch consumer queue file may loss**

**Comment by Ah39** [comment]
if last consumer queue flush success ，logicsMsgTimestamp is 11:14
the new time is
physicMsgTimestamp 11:17
logicsMsgTimestamp = 11:16
indexMsgTimestamp = 11:16
when index file flush , but the 11:16 consumer queue file dont flush .
So may from 11:14 to 11:16 dispatch consumer queue file may loss

**Comment by MountainOne** [comment]
When the index file is successfully flushed, the message queue consumption file is not successfully flushed and the machine is crash, which may cause the message consumption queue file to be lost. But as long as the commitlog file is not lost, you can use RocketMQ's file recovery mechanism to recover lost message consumption queue files.
In RocketMQ's file recovery mechanism, there is a mechanism for file recovery for abnormal downtime. When the broker starts abnormally, during the file recovery process, RocketMQ forwards all the messages of the last valid file to the message consumption queue and index file, ensuring that no messages are lost, but also causes repeated consumption problems. Looking at RocketMQ As a whole design idea, RocketMQ guarantees that the message is not lost but does not guarantee that the message will not be repeatedly consumed. Therefore, the message consumer business party needs to realize the idempotent design of message consumption.
Tip: RocketMQ has two file recovery mechanisms, normal shutdown recovery and abnormal downtime recovery. The way to determine the exception is to create an abort empty file when the broker starts, and delete the file at the normal end. The next time you start the broker, if you find the abort file, it is considered abnormally down, otherwise, it is a normal shutdown.

当索引文件刷盘成功，消息队列消费文件未刷盘成功且宕机时，会造成消息消费队列文件丢失的问题。但只要 commitlog 文件没有丢失，就可以利用 RocketMQ 的文件恢复机制，恢复丢失的消息消费队列文件。
在 RocketMQ 的文件恢复机制中，有针对异常宕机进行文件恢复的机制。当 broker 异常启动，在文件恢复过程中，RocketMQ 会将最后一个有效文件的所有消息转发到消息消费队列和索引文件，确保不丢失消息，但同时也会带来重复消费的问题，纵观 RocketMQ 的整体设计思想，RocketMQ 保证消息不丢失但不保证消息不会重复消费，故消息消费业务方需要实现消息消费的幂等设计。
提示：RocketMQ 有两种文件恢复机制，正常关机恢复和异常宕机恢复。判断异常的方式是在 broker启动的时候创建一个 abort 空文件，在正常结束的时候删掉这个文件。在下一次启动 broker 时，如果发现了 abort 文件，则认为是异常宕机，否则就是正常关机。
