### ISSUE TITLE
Broker开启--enable-proxy后配置了namesrvAddr属性没有作用，启动时报错

### ISSUE THREAD

**Issue by zzz-workstation** [apache/rocketmq#6868]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

CentOS7 
jdk1.8
rocketmq-5.1.1

### RocketMQ version

rocketmq-5.1.1

### JDK Version

jdk1.8

### Describe the Bug

我在部署集群时，指定了配置borker-a.properties配置文件，配置属性如下：
![image](https://github.com/apache/rocketmq/assets/12889183/b3127732-b8f2-41cb-8aa1-fe0fd4532b3c)

在配置中我明确的配置了namesrvAddr=192.168.31.131:9876;192.168.31.132:9876;192.168.31.133:9876。但是，当我使用以下命令启动时，会出现 **java.lang.RuntimeException: The configuration item NamesrvAddr is not configured**错误，导致无法启动

`nohup sh bin/mqbroker -c conf/2m-2s-async/broker-a.properties --enable-proxy &`

![image](https://github.com/apache/rocketmq/assets/12889183/2353e2ee-8c60-43fc-a84a-2ee6d9d0d61c)

如果我在启动的命令中指定namesrvAddr却是可以正常启动，用以下命令可以正常启动。

`nohup sh bin/mqbroker -n 192.168.31.131:9876 -c conf/2m-2s-async/broker-a.properties --enable-proxy &`

为什么会出现这种情况？

### Steps to Reproduce

Broker配置了namesrvAddr属性没有作用，启动时会报java.lang.RuntimeException: The configuration item NamesrvAddr is not configured

### What Did You Expect to See?

启动时指定了配置文件，应该使用配置文件中的namesrvAddr，但没有使用，而且还报错了

### What Did You See Instead?

启动时指定了配置文件，应该使用配置文件中的namesrvAddr，但没有使用，而且还报错了

**Comment by ltamber** [comment]
在 conf/rmq-proxy.json 里配置下 namesrvAddr 试试

**Comment by f1amingo** [comment]
Take a look at the `bin/mqbroker` script file and you will understand.
If you specify the option `--enable-proxy`, it will start Proxy instead of Broker.
Proxy and Broker are two components that can be deployed separately, so they use different configuration files.
Proxy takes below CLI arguments, that's why your option `-n 192.168.31.131:9876` works.
You should use `-pc` to specify Proxy configuration file.
![image](https://github.com/apache/rocketmq/assets/29991810/db8ad969-06d8-461a-98a9-4d74e9d1d549)
