### ISSUE TITLE
[Bug] the queue's messages, span too long, so do flow control

### ISSUE THREAD

**Issue by lfs1985** [apache/rocketmq#7134]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

centos7.0

### RocketMQ version

4.7.1

### JDK Version

jdk1.8

### Describe the Bug

There are many warn logs in the production environment。
![image](https://github.com/apache/rocketmq/assets/44808351/16803beb-7565-4b54-91ae-6a7a00773daf)
The message has been processed，but the client's (in processQueue)minOffset no changed for long time。 
Restart the client, the problem can be solved, but many messages will be repeated consumpted。
We try to reproduce it，but have no result。

### Steps to Reproduce

We try to reproduce it，but have no result。

### What Did You Expect to See?

The client's minOffset  can changed。

### What Did You See Instead?

The client's minOffset no changed for a long time, at least one month.

### Additional Context

no

**Comment by cserwen** [comment]
It should be caused by this problem  https://github.com/apache/rocketmq/pull/3861

As for the reason for throwing an exception, it may be that `PROPERTY_CONSUME_START_TIMESTAMP` has not been set when cleaning up the expired message, so an exception is thrown at here.
https://github.com/apache/rocketmq/blob/9f95a972e10e0681bc3f2d00e9957aa212e897b5/client/src/main/java/org/apache/rocketmq/client/impl/consumer/ProcessQueue.java#L88C1-L89C1
