### ISSUE TITLE
[Enhancement] Integration test testEstimateLag can not pass

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq#7765]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Integration test testEstimateLag can not pass

### Motivation

Integration test testEstimateLag can not pass

### Describe the Solution You'd Like

Fix the test or related code

### Describe Alternatives You've Considered

No

**Comment by luvgupta014** [comment]
can I fix it?

**Comment by RongtongJin** [comment]
> can I fix it?
Of course

**Comment by UWEPPPP** [comment]
Has it been completed? I would also like to give it a try.

**Comment by UWEPPPP** [comment]
This issue is related to the 'develop' branch, right? I couldn't reproduce the test failure in the 5.1.4 branch.

> Has it been completed? I would also like to give it a try.

This issue is related to the 'develop' branch, right? I couldn't reproduce the test failure in the 5.1.4 branch.

**Comment by RongtongJin** [comment]
> This issue is related to the 'develop' branch, right? I couldn't reproduce the test failure in the 5.1.4 branch.
> 
> > Has it been completed? I would also like to give it a try.
> 
> This issue is related to the 'develop' branch, right? I couldn't reproduce the test failure in the 5.1.4 branch.

Yes, in develop branch. You can submit a PR to fix it.

**Comment by UWEPPPP** [comment]
I cannot reproduce testEstimateLag's test failure unless it fails when my disk space is less than 10% causing the DefaultMessageStore.isSpaceToDelete() function to trigger the file to be deleted. So sir, does your question refer to this?
&nbsp;


刘家辉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月27日(星期六) 晚上11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/rocketmq] [Enhancement] Integration test testEstimateLag can not pass (Issue #7765)





  
This issue is related to the 'develop' branch, right? I couldn't reproduce the test failure in the 5.1.4 branch.
  
Has it been completed? I would also like to give it a try.
  
This issue is related to the 'develop' branch, right? I couldn't reproduce the test failure in the 5.1.4 branch.
  
Yes, in develop branch. You can submit a PR to fix it.

**Comment by UWEPPPP** [comment]
> > This issue is related to the 'develop' branch, right? I couldn't reproduce the test failure in the 5.1.4 branch.
> > > Has it been completed? I would also like to give it a try.
> > 
> > 
> > This issue is related to the 'develop' branch, right? I couldn't reproduce the test failure in the 5.1.4 branch.
> 
> Yes, in develop branch. You can submit a PR to fix it.

I cannot reproduce testEstimateLag's test failure unless it fails when my disk space is less than 10% causing the DefaultMessageStore.isSpaceToDelete() function to trigger the file to be deleted. So sir, does your question refer to this?

**Comment by GenerousMan** [comment]
@UWEPPPP I have reproduced the issue, but my disk is far from full. It's very stable to reproduce.

![image](https://github.com/apache/rocketmq/assets/21073949/a37579f7-840a-45c2-9f9e-fb01e519ad6d)
